# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BoardGameSupport' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BoardGameSupport
  # MVVM架構
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'  # 讓M1晶片的MAC可編譯
      config.build_settings['LD_NO_PIE'] = 'NO'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end
